config/routes.rb
Rails.application.routes.draw do
  # PAGES
  get 'pages/index'
  get 'pages/about'
  get 'pages/team'
  root 'pages#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def about
  end

  def team
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Primer Proyecto en Rails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="is-preloaded">
    <div id="wrapper">
      <header id="header">
        <div class="inner"> 
          <nav>
            <ul>
              <li><a href="#menu">Menu</a></li>
            </ul>
          </nav>
        </div>
      </header>
   
      <!-- Menu -->
      <nav id="menu">
        <h2>Menu</h2>
        <ul>
          <li> <%= link_to "Index", pages_index_path %> </li>
          <li>  <%= link_to "About", pages_about_url %> </li>
          <li> <%= link_to "Ruby On Rails", pages_team_path %> </li>
        </ul>
      </nav>
    <% # A la hora de generar links internos es mejor ocupar _path, ya que no necesitamos saber cual es el dominio del sitio en el que estamos navegando. Pero si necesitamos incluir el dominio como por ejemplo, cuando se envía un link de cambio de contraseña, entonces en ese caso debemos usar el sufijo _url. En la gran mayoría de los casos simplemente ocuparemos _path y señalaremos cuando haya que ocupar _url %>

    <!-- Main -->
  <div id="main">
    <div class="inner">
      <%= yield %>
    </div>
  </div>
 
  <!-- Footer -->
<footer id="footer">
  <div class="inner">
  <ul class="copyright">
  <li>
    ©Copyright <%= Time.now.year %>
 <% if Time.now.year >= 2020 %>
<h3>Version 2.0</h3>
<% else %>
<h3>Version 1.0</h3>
<% end %> </li>
  </li><li>Iván Carrasco <a
  href="https://alexcct107.github.io/aztlan_portfolio/">Estudios Aztlán</a></li>
  </ul>
  </div>
  </footer>
  </div>

  </body>
  <%= javascript_include_tag 'application' %>
</html>

app/views/pages/about.html.erb
<h1>Sobre Mí</h1>
<p>Soy Iván 🤟🏼 y amo los videojuegos, crear páginas y aplicaciones web, viajar y comer. Espero convertirme en un buen desarrollador web full stack pronto y así poder crear proyectos asombrosos.</p>
<h3>Bienvenidos a mi primera Página web en Rails</h3>

app/views/pages/index.html.erb
<h1>Hola soy Iván Carrasco</h1>
<h2>Esta es Mi primera página Web</h2>
<h2>Bienvenidos Amigos</h2>

app/views/pages/team.html.erb
<h1>Creado con Ruby On Rails en Desafío LATAM</h1>
<div> <%= image_tag "ruby.png" %> </div>
<h2>Aqui se programa en Ruby On Rails ❤️</h2>